services:
  test-endpoint:
    image: nginx:alpine
    networks: 
      endpoint-net:  # Private network, not accessible from outside
    volumes:
      - ./test-endpoint/html:/usr/share/nginx/html:ro
      - ./test-endpoint/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./test-endpoint/certs:/etc/nginx/certs:ro
    expose:
      - "443"
    environment:
      - PYTHONUNBUFFERED=1

  dns-server:
    build:
      context: .
      dockerfile: server_Dockerfile
    ports:
      - "53:53/udp"
    networks:
      - proxy-net
      - endpoint-net  # Can access the test endpoint
    environment:
      - PYTHONUNBUFFERED=1
      - PROXY_CLIENT_ADDRESS=client

  client:
    build:
      context: .
      dockerfile: client_Dockerfile
    ports:
      - "1080:1080"
    networks:
      - proxy-net  # Can only access dns-server
    environment:
      - PYTHONUNBUFFERED=1
      - PROXY_SERVER_ADDRESS=dns-server
    depends_on:
      - dns-server
      - test-endpoint

networks:
  proxy-net:
    driver: bridge
  endpoint-net:  # Private network for test endpoint
    driver: bridge
    internal: true  # Makes this network internal only